# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Retifex
tagline:          'A Jekyll theme'
description:      ''
url:              krzjoa.github.com
baseurl:          /

author:
  name:           'Krzysztof Joachimiak'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/krzjoa.github.com
